version : "3.8"

Service:
  nginx:
    image: nginx:latest
    container_name: nginx
    volume:
      - /var/www/html:/user/share/nginx/html 
      - /home/html:/user/share/nginx/html


  jenkins:
    image: jenkins/jenkins:lts
    container_name: Jenkins
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
