version : "3.8"
Service:
  nginx:
    image: nginx:latest
    volume:
      - /var/www/html 
      - /home/html


services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent
volumes:
  jenkins_home:
